<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerObmdzgt\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerObmdzgt/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerObmdzgt.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerObmdzgt\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerObmdzgt\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Obmdzgt',
    'container.build_id' => '71653828',
    'container.build_time' => 1537328738,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerObmdzgt');
